stages:
  - testing

variables:
  SHORT_URL_API_BASE_URL: ${SHORT_URL_API_BASE_URL}
  SHORT_URL_API_ID: ${SHORT_URL_API_ID}
  SHORT_URL_API_TOKEN: ${SHORT_URL_API_TOKEN}

running test suite:
  stage: testing
  script:
    - composer install --optimize-autoloader
    - ./vendor/bin/phpunit --testdox
  tags:
    - short-url-package
  only:
    - tests
