stages:
  - building
  - testing

variables:
  SHORT_URL_API_BASE_URL: ${SHORT_URL_API_BASE_URL}
  SHORT_URL_API_ID: ${SHORT_URL_API_ID}
  SHORT_URL_API_TOKEN: ${SHORT_URL_API_TOKEN}

installing dependencies:
  stage: building
  script:
    - composer install --optimize-autoloader
  tags:
    - short-url-package

running test suite:
  stage: testing
  script:
    - cp phpunit.xml.dist phpunit.xml
    - ls
    - ./vendor/bin/phpunit
  tags:
    - short-url-package
  only:
    - tests
